### ISSUE TITLE
Wie kann ich Zählerwerte aus einer API einbauen?

### ISSUE THREAD

**Issue by colseven** [mb-software/homeassistant-powerbrain#61]
Wenn ich das richtig gelesen habe kann man http Messwerte an den Lademanager übergeben, leider habe ich diesbezüglich nichts gefunden. Wie kann ich die machen?
Danke.

**Comment by mb-software** [comment]
You have to add a meter of type Http In in your powerbrain configuration. Then by using the powerbrain.set_meter service and passing the powerbrain device id in HA you can send values to this meter.
