### ISSUE TITLE
Control - Switches jump back to the previous status

### ISSUE THREAD

**Issue by Unwies** [mb-software/homeassistant-powerbrain#67]
Hey…

I have a cFos Power Brain,2.0,1.20.2,W00-03HK (11 kw Solar version) and Home Assistant 2023.7.2 installed.

The integration works fine with all sensors (measurements).

but the control panel with the switches doesn’t work for me. If I switch off as an example “Wallbox Charging Rules Enabled” the status changes for a second and then it jumps back to “on”. 

Is there anything I need to configure in the wallbox or HA?

and by the way… how to use pin/rfid via HA… is there any kind of documentation?

Beside this, thanks for your work and this nice implementation 

jörg

**Comment by mb-software** [comment]
Do you have a car connected to the cfos? I think without a car connected you cannot enable/disable charging rules etc.  These options are then also not accessible in the cfos web-ui.
Regarding the RFID function: please check the enter_RFID homeasistant service. The parameters are documented and should be rather self explanatory. Just call the service to enter a RFID.

**Comment by Unwies** [comment]
Hey Markus,

you are right with a car connected it works. Many thanks.

**Comment by TribuneX** [comment]
Could we take the connected state into account to represent the switch state?

Would be nice if the switch could stay off / deactivated in case no car is connected.
