### ISSUE TITLE
Charging process is not counted correctly - always 0 kWh when automation switches 16 A

### ISSUE THREAD

**Issue by colseven** [mb-software/homeassistant-powerbrain#70]
Running firmware version: 1.20.4, found 1.20.4

Whenever I start a charging process and have it charged via HA, the kWh are also counted correctly. However, if I press a switch that switches the charging power directly to 16A per phase via automation, 0 kWh is always displayed in the end! I've tried this several times ... if I start in a controlled manner, it also counts in the log, if I then increase the charging power to 16A, it continues to count - when the charging process is complete, however, there is always a 0.

![bild 2023-08-01 um 18 38 22](https://github.com/mb-software/homeassistant-powerbrain/assets/63189272/e8d8607a-6665-4d17-872c-aa020eba23bd)

`if:
  - condition: trigger
    id: Voll
then:
  - service: notify.alexa_media_christianes_echo_dot_2
    data:
      message: Wallbox Volle Lotte
  - service: automation.turn_off
    data:
      stop_actions: true
    target:
      entity_id: automation.go_e_charger_1_kw_2
  - device_id: 81f9c87a238b9953b0fcc8b26acbe536
    domain: number
    entity_id: number.wallbox_current_limit_override
    type: set_value
    value: 16
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: sensor.wallbox_charging_power
        below: 2000
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.go_e_charger_1_kw_2`

**Comment by mb-software** [comment]
This is probably not related to this integration as the integration has no influence on the charged kWh counted by the powerbrain itself. The integration only sends the current overwrite setpoint via the API. I guess you will have to address this issue directly to cFos.
