### ISSUE TITLE
Connecting using HTTPS not possible

### ISSUE THREAD

**Issue by dylan09** [mb-software/homeassistant-powerbrain#72]
Hello

I have added a certificate for web access to my wallbox. No I tried to add the integration using https://...
But always get an error telling me, connection failed. Is https not supported by the integration?

**Comment by mb-software** [comment]
I have to admit that I have not tested it with https connections and currently I have no powerbrain with enabled https to try it out myself.
But normally there should be not much difference connecting via https and it should work similarly. Do you use a verified certificate or is it a self signed certificate (which will also give you a security warning in a webbrowser)?

Maybe someone else also using https can verify the issue.

**Comment by dylan09** [comment]
I am using a self-signed certificate. 

But I had to push pack the tests using https. There seems to be a problem with the powertrain HTTP Server. Seems it is crashing when using https with safari on macOS. 
Will check this with the cfos support.
