### ISSUE TITLE
Integration needs Internet access to work with local wallbox

### ISSUE THREAD

**Issue by dylan09** [mb-software/homeassistant-powerbrain#84]
Today we had a failure with our network provider. During the failure there was no internet available.
During this failure the integration stops working and all devices / entities from my local wallbox was unavailable.

The web interface of the wallbox was available through web browser all the time.

Why is the integration depending on internet access for my local available wallbox?

**Comment by mb-software** [comment]
This integration does not need an internet connection, it works over local network. There is nothing in the code that would require internet access.
Anyway, I just made the test and switched of my internet modem. As expected the integration was still working like normal. In your case something else must have caused the issue.

**Comment by dylan09** [comment]
Thanks for clarification. Will test again what happens when I shutdown my internet connection.
