### ISSUE TITLE
Display which car is currently charging + separate counters for each car?

### ISSUE THREAD

**Issue by colseven** [mb-software/homeassistant-powerbrain#86]
Since I charge several cars with RFID, I would like to know via entity which car is currently charging so that I can then build a separate meter for each car. Is that somehow possible?

**Comment by mb-software** [comment]
A separate counter for each car is certainly something that you would have to implement in your HA automations/logic.
To get the ID of the connected car you could maybe set a charging manager variable from your charging rules that gets activated with the RFID. Then you can use this ID in a virtual meter (type expression) and read it with HA.
It's a little complicated but it should be possible.

**Comment by colseven** [comment]
What exactly would such a charging rule have to look like? I charge three different cars at the box, so a separate count via HA would be great, but for that I would have to know which car is currently charging.
